(ns personal-website.content.writings.blog-posts.reaction-diffusion-systems-and-turing-patterns
  (:require [personal-website.utils :as utils]
            [garden.stylesheet :refer [at-media]]))

(def post-preview [:p "As part of an independent research project in my chemistry class,
       I decided to take a closer look at reaction-diffusion systems and
       the role they play in Alan Turing's theory of morphogenesis. Here's what
       came of it."])

(def post-content
  [:div
   [:p "The biological world is replete with astouding imagery. One
        doesn't have to look far to find evidence of this. From a
        leopard's spots, to a tiger's stripes, and the dizzying
        labrynth-like patterns on a pufferfish, there is pattern
        upon pattern."]

        [:figure {:class "img-container"}
         [:div {:style {:text-align "center"}}
          [:img {:src "turing-pattern-1.jpg" :style {:width "25%" :margin-right "5%" :margin-left "0%"}}]
          [:img {:src "turing-pattern-2.jpg" :style {:width "27.5%"}}]
          ;[:img {:src "turing-pattern-3.jpg" :style {:width "31%" :margin-right "7%"}}]
          [:img {:src "turing-pattern-5.jpg" :style {:width "32%" :margin-left "5%"}}]
           [:figcaption {:class "post-caption" :style {:text-align "left"}}
           "Fig. 1. Examples of surfaces generated by a function of two variables (Source: "
            (utils/link "CalcPlot3D" "https://www.monroecc.edu/faculty/paulseeburger/calcnsf/CalcPlot3D/")")."]]]


  [:p "What could be the generating function for such
  variance – what one process could be capable? These were
  the questions Alan Turing, as he sought to extend
  the computability to biology"]

        [:h1 {:class "post-section-header"} "Vector Calculus Review"]

        [:p "Reaction diffusion systems model how to fluids interact with
             eachother. We'll imagine its a 2D plane. Like in all
              can represent some vector valued function as a vector field.
             In particular, we often deal with the two-dimensional case."]

        [:p "Then divergence is just a very natural question about this vector
             field. At a specific point on this field, is the fluid flowing toward
             it or away?"]
   ])






(def post
  {:title "Reaction-Diffusion Systems And Turing Patterns"
   :date "12/22/2020"
   :show post-preview
   :content post-content
   :tags ["mathematics", "deep learning"]
   :type "blog-post"
   :overarching "writing"
   :id "1"
   :css ""})
